networks:
    default:
        driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/wordpress
      o: bind

  db:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/mariadb
      o: bind

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    volumes:
      - wp:/var/www/html
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp:/var/www/html
    env_file: .env
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 3

  redis:
    container_name: redis
    build: requirements/redis
    restart: unless-stopped

  ftp:
    build: requirements/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wp:/ftp-data
    environment:
      FTP_PASSWORD: $FTP_PASSWORD
    restart: unless-stopped
